config/routes.rb
Hera::Application.routes.draw do

  get 'report' => "report#report"
  post 'report_print' => "report#report_print"
  get 'report/config' => "report#report_config"
  post 'report/config_save' => "report#report_config_save"

  devise_for :users, controllers: {users: "users"}

  devise_scope :users do
    get 'users/login' => 'devise/sessions#new'
    get 'users/logout' => 'devise/sessions#destroy'
  end

  resources :web_services_posts
  get "web_services/web_post" => "web_services_post#web_post"

  resources :web_services_gets
  get "web_services/get_checklist" => "web_services_get#get_checklist"
  get "web_services/get_building_name" => "web_services_get#get_building_name"

  get "equipment/disapprove"
  get "equipment/validate"
  get "inspections/disapprove"
  resources :web_servicess
  get "web_services/teste_mobile" => "web_services#teste_mobile"
  get "web_services/get_building_png" => "web_services#get_building_png"
  get "web_services/get_usp_png" => "web_services#get_usp_png"
  get "web_services/get_num_pav" => "web_services#get_num_pav"
  get "web_services/get_usp_map_info" => "web_services#get_usp_map_info"
  get "web_services/get_id_by_coordinate" => "web_services#get_id_by_coordinate"
  get "web_services/get_building_info" => "web_services#get_building_info"
  get "web_services/get_gml_by_code" => "web_services#get_gml_by_code"

  resources :equipment
  get "inspections/index_history"
  get "inspections/validate"
  post "inspections/validate"
  get "inspections/disapprove"
  post "inspections/disapprove"
  
  get "inspections/removephoto" => "inspections#removephoto"
  
  resources :inspections

  resources :groups

  get "buildings/groups" => "buildings#groups"
  get "buildings/groups/detail" => "buildings#groupsdetail"
  
  resources :buildings

  

  resources :user

  resources :equip_types

  get "home" => "home#index"
  
  get "tutorial/passoapasso" => "tutorial#passoapasso"
  
  get "configuration/index"

  root 'welcome#welcome'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :inspection
	belongs_to :checklist_item
  
  has_many :upload
end

app/models/building.rb
class Building < ActiveRecord::Base
	has_many :equipment
	has_many :groups

	validates :idAtlas, uniqueness: true, presence: true
end

app/models/checklist_item.rb
class ChecklistItem < ActiveRecord::Base
	belongs_to :equip_type
	has_many :answers

	validates :question, presence: true
	#validates :question, uniqueness: true
end

app/models/equip_type.rb
class EquipType < ActiveRecord::Base
	self.inheritance_column = nil
	has_many :equipment
	has_many :inspections, :through => :equipment
	has_many :checklist_items
  
  accepts_nested_attributes_for :checklist_items, allow_destroy: true

	validates :kind, presence: true
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	has_many :inspections, :dependent => :delete_all
	belongs_to :equip_type
	belongs_to :building

	validates :is_there, :inclusion => {:in => [true, false]}
  
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :inspections
  belongs_to :building

end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
  belongs_to :equipment
  has_many :answers

  delegate :equip_type, :to => :equipment 

	mount_uploader :photo_url, PictureUploader
end

app/models/report_config.rb
class ReportConfig < ActiveRecord::Base
	def self.clear
		self.connection.execute("DELETE FROM reportconfig")
	end
	
	def self.read
		self.connection.execute("SELECT equip_types.kind,reportconfig.id_checklist FROM reportconfig JOIN equip_types ON reportconfig.id_checklist = equip_types.id").to_a
	end
	
	def self.readidonly
		self.connection.execute("SELECT reportconfig.id_checklist FROM reportconfig").to_a
	end

	def self.update (data)
		self.clear
		data.each do |d|
			self.connection.execute(sanitize_sql(["INSERT INTO reportconfig (id_checklist,created_at,updated_at) VALUES (?,?,?)",d.to_i,Date.today.to_s,Date.today.to_s]))
		end		
	end	
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_attached_file :photo
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  belongs_to :answer

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	self.inheritance_column = nil
	has_many :inspections

	validates :nusp, uniqueness: true
  
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def index
    @blds = Building.all.order(:name)
  end
  
  def new
    @bld = Building.new
  end
  
  def show
  end
  
  def create
    bld = Building.new
    bld.update_attributes(building_params)
    bld.save
    redirect_to buildings_path
  end
  
  def edit
    @bld = Building.find_or_create_by_id(params[:id])
  end
  
  def update
    bld = Building.find params[:id]
    bld.update_attributes(building_params)
    bld.save
    redirect_to buildings_path
  end

  def groups
    @blds = Building.all.order("name ASC")
  end

  def groupsdetail 
    @local = Building.find(params[:id])
    @groups = Group.where(building_id: params[:id]).order("name ASC")
  end
  
  def building_params
    params.require(:building).permit(:name,:idAtlas)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    
  end
  
end

app/controllers/kbox_controller.rb
class MessengerController < ApplicationController
  def box
  	@messages = nil
  	@mode = param[:box]
  	
  	if (@mode nil?)
  		@mode = "inbox"
  	end
  	
  	if (@mode == "inbox")
  		@messages = MSMessage.where(:id = 0)
  	end
  	else if (@mode == "sent")
  		@messages = MSMessage.where(:id = 0)
  	end
  	else if (@mode == "important")
  		@messages = MSMessage.where(:id = 0)
  	end
  	else if (@mode == "bin")
  		@messages = MSMessage.where(:id = 0)
  	end
  	
  end
  
  def compose
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def index
    @inspections = Inspection.all
    @equipTypes = EquipType.all
    @users = User.all
    @users = @users.where("name like ?", "%#{params[:search]}%") unless params[:search].blank?
    @users = @users.where("kind = ?", params[:user_type]) unless params[:user_type].blank?
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find params[:id]
    @roles = [["Administrador/Aprovador","admin"],["Normal","normal"]]
    @role = @user.kind

    if (@role.nil?)
      @role = "normal"
    end
  end

  def update
    user = User.find params[:id]
    user.update_attributes(userdata_params)
    user.save
    redirect_to user_path(params[:id])
  end

  def userdata_params
    params.require(:user).permit(:name,:nusp,:cpf,:kind)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/building_helper.rb
module BuildingHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/gerenciamento_helper.rb
module GerenciamentoHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/inspection_helper.rb
module InspectionHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/web_services_helper.rb
module WebServicesHelper
end

app/views/buildings/edit.html.erb
<%= nested_form_for @bld do |f| %>
  <%= f.label :name, "Nome" %>
  <%= f.text_field :name %>

  <%= f.label :idAtlas, "ID Atlas" %>
  <%= f.text_field :idAtlas %>'

  <br/>
  <%= f.submit "Salvar" %>
  
<%end%>

app/views/buildings/groups.html.erb
<table class="table table-striped table-hover">
    <tr>
        <th>Nome</th>
        <th>Número de Vistorias</th>
        <th></th>
    </tr>
    <% @blds.each do |bld| %>
        <tr>
            <td>
               <%= label "", bld.name, "" %>
            </td>
            <td>
	      	<% count = Group.where(building_id: bld.id).count %>
	      	<% if count > 0 %>
               		<%= link_to count , buildings_groups_detail_path(id: bld.id) %>
		<% else %>
			<%= label "", 0 , "" %>
		<% end %>
            </td>
        </tr>
    <% end -%>
</table>

app/views/buildings/groupsdetail.html.erb
<h2>Localização: <%= @local.name %></h2>
<table class="table table-striped table-hover">
    <tr>
        <th>Vistoria</th>
        <th></th>
    </tr>
    <% vistoria = 1 %>
    <% @groups.each do |grp| %>
        <tr>
          <td>
		<%= link_to "Vistoria #" + vistoria.to_s + " " + grp.name + " - " + grp.vist_date.to_s , group_path(id: grp.id) %>
		<% vistoria = vistoria + 1 %>
          </td>
	  <td>
		<%= link_to "Gerar Relatório" , report_path(id: grp.id, t: 2) %> 
	  </td>
        </tr>
    <% end %>
</table>

app/views/buildings/index.html.erb
<i><%= link_to "[Criar Nova Localização]", new_building_path %></i>
<br/>
<table class="table table-striped table-hover">
    <tr>
        <th>Nome</th>
        <th>ID Atlas</th>
        <th></th>
    </tr>
    <% @blds.each do |bld| %>
        <tr>
            <td>
               <%= label "", bld.name, "" %>
            </td>
            <td>
               <%= label "", bld.idAtlas, "" %>
            </td>

            <td><%= link_to "Editar", edit_building_path(:id => bld.id) %>
        </tr>
    <% end -%>
</table>

app/views/buildings/new.html.erb
</br>
<font size="3"><b>Novo prédio</b></font>

<%= nested_form_for @bld do |f| %>
  </br>
  <%= f.label :name, "Nome" %>
  <%= f.text_field :name %>

  <%= f.label :idAtlas, "ID Atlas" %>
  <%= f.text_field :idAtlas %>'

  <br/>
  <%= f.submit "Criar", :class => "btn default-button" %>

<%end%>