config/routes.rb
Hera::Application.routes.draw do

  get 'report' => "report#report"
  post 'report_print' => "report#report_print"
  get 'report/config' => "report#report_config"
  post 'report/config_save' => "report#report_config_save"

  devise_for :users, controllers: {users: "users"}

  devise_scope :users do
    get 'users/login' => 'devise/sessions#new'
    get 'users/logout' => 'devise/sessions#destroy'
  end

  resources :web_services_posts
  get "web_services/web_post" => "web_services_post#web_post"

  resources :web_services_gets
  get "web_services/get_checklist" => "web_services_get#get_checklist"
  get "web_services/get_building_name" => "web_services_get#get_building_name"

  get "equipment/disapprove"
  get "equipment/validate"
  get "inspections/disapprove"
  resources :web_servicess
  get "web_services/teste_mobile" => "web_services#teste_mobile"
  get "web_services/get_building_png" => "web_services#get_building_png"
  get "web_services/get_usp_png" => "web_services#get_usp_png"
  get "web_services/get_num_pav" => "web_services#get_num_pav"
  get "web_services/get_usp_map_info" => "web_services#get_usp_map_info"
  get "web_services/get_id_by_coordinate" => "web_services#get_id_by_coordinate"
  get "web_services/get_building_info" => "web_services#get_building_info"
  get "web_services/get_gml_by_code" => "web_services#get_gml_by_code"

  resources :equipment
  get "inspections/index_history"
  get "inspections/validate"
  post "inspections/validate"
  get "inspections/disapprove"
  post "inspections/disapprove"
  
  get "inspections/removephoto" => "inspections#removephoto"
  
  resources :inspections

  resources :groups

  get "buildings/groups" => "buildings#groups"
  get "buildings/groups/detail" => "buildings#groupsdetail"
  
  resources :buildings

  

  resources :user

  resources :equip_types

  get "home" => "home#index"
  
  get "tutorial/passoapasso" => "tutorial#passoapasso"
  
  get "configuration/index"

  root 'welcome#welcome'

end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
  belongs_to :equipment
  has_many :answers

  delegate :equip_type, :to => :equipment 

	mount_uploader :photo_url, PictureUploader
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
	before_filter :authenticate_user!

    def show
        @inspection = Inspection.find(params[:id]);
        @answers = Answer.where(inspection_id: params[:id])
        prepared_url = @inspection.photo_url.to_s
        prepared_url.slice!(0)
	if prepared_url == ""
		@inspection_url = nil
	else
        	@inspection_url = root_url + prepared_url
	end
    end

    def validate
        if (current_user.kind == "admin")
            @inspection = Inspection.find(params[:id])
            @inspection.update_column :approved, 1
            redirect_to action: :show, id: @inspection.id
        else
            redirect_to action: :show, id: @inspection.id
        end
    end

    def disapprove
        if (current_user.kind == "admin")
            @inspection = Inspection.find(params[:id])
            @inspection.update_column :approved, 2
            redirect_to action: :show, id: @inspection.id
        else
            redirect_to action: :show, id: @inspection.id
        end
    end

  def new
    @inspection = Inspection.new
    @equipments = Equipment.all.order(:name).collect{|p| [p.name,p.id]}
    @equipment = 0
  end

  def create
    inspection = Inspection.new
    inspection.update_attributes(inspection_params)
    identificacao = inspection.equipment_id
    condicao = Equipment.find(identificacao)
    inspection.save

    if condicao.is_there
        redirect_to edit_inspection_path(inspection.id)
    else
        redirect_to root_path
    end
  end

  def edit
    @inspection = Inspection.find(params[:id])
    @questions = @inspection.equipment.equip_type.checklist_items.collect{|p| [p.id, p.question] }
    @answertypes = [["Sim",0],["Nao",1], ["Nao se Aplica",2],["Nao Respondido",999]]
    @answer_data = Answer.where(inspection_id: params[:id])
    @answer_test = @answer_data.where(checklist_item_id: 29)
    
  end

def update
	inspection = Inspection.find params[:id]
	inspection.group_id = params[:inspection][:group_id]
	inspection.save
	answer_data = params[:answers]
	answer_data.each do |answer|
		answer_db = Answer.where(inspection_id: inspection.id, checklist_item_id: answer[0])
		answer_db_data = answer_db.first #passa de relation para o objeto que precisamos

		photo_data = nil

		if (!params[:photos].nil?)
			photo_data = params[:photos][answer[0]]
		end

		if (answer_db_data.nil?)
			answer_new = Answer.new
			answer_new.inspection_id = inspection.id
			answer_new.checklist_item_id = answer[0]
			answer_new.is_ok = answer[1]
			answer_new.comment = params["comment_" + answer[0].to_s]
			answer_new.save

			#upload!
			if (!photo_data.nil?)
				photo_data.each do |photo|
				new_upload = Upload.new
				new_upload.answer_id = answer_new.id
				new_upload.photo = photo
				new_upload.save	
			end
		end
		else
			answer_db_data.is_ok = answer[1]
        		answer_db_data.comment = params["comment_" + answer[0].to_s]
        		answer_db_data.save

        		#upload!
        		if (!photo_data.nil?)
          			photo_data.each do |photo|
            				new_upload = Upload.new
            				new_upload.answer_id = answer_db_data.id
            				new_upload.photo = photo
            				new_upload.save
          			end
        		end
      		end

		#process the removals?
		to_remove = params["removal_" + answer[0].to_s]
		if (!to_remove.nil?)
			@a = 0
		end
    	end
   	redirect_to inspection_path id: inspection.id
end

def removephoto
	if (params[:idphoto].nil?)
		raise ActionController::RoutingError.new('Invalid ID!')
	end;
	if (current_user.kind == "admin")
		photo_to_remove = Upload.find(params[:idphoto])
		if (photo_to_remove.nil?)
			raise ActionController::RoutingError.new('Invalid ID!')
		end
		photo_to_remove.delete
		photo_to_remove.save
	else
		raise ActionController::RoutingError.new('Unauthorized!')
	end
end

def index
		@equip_types = EquipType.order("kind").all
		@users = User.order("name").where(kind: "estag")
		@groups = Group.all.order("name")
		@buildings = Building.order("name").all

		@inspections = Inspection.where(approved: 0).order("created_at DESC")
		@inspections = @inspections.where("user_id = ?", params[:user_id]) unless params[:user_id].blank?
		@inspections = @inspections.where("group_id = ?", params[:group_id]) unless params[:group_id].blank?

		@inspections = @inspections.joins(:equipment).where(equipment: {equip_type_id: params[:equip_type_id]}) unless params[:equip_type_id].blank?
		@inspections = @inspections.where("inspections.created_at > ?", params[:data1]) unless params[:data1].blank?
		@inspections = @inspections.where("inspections.created_at < ?", params[:data2]) unless params[:data2].blank?
		@inspections = @inspections.joins(:equipment).where(equipment: {building_id: params[:building_id]}) unless params[:building_id].blank?
		@inspections = @inspections.where(equipment_id: params[:equipment_id]) unless params[:equipment_id].blank?
	end

	def index_history
		@equip_types = EquipType.order("kind").all
		@users = User.order("name").where(kind: "estag")
		@buildings = Building.order("name").all
		@groups = Group.all

		@inspections = Inspection.where("approved <> 0 AND NOT approved = 2").order("created_at DESC")
		@inspections = @inspections.where("user_id = ?", params[:user_id]) unless params[:user_id].blank?

		@inspections = @inspections.where("group_id = ?", params[:group_id]) unless params[:group_id].blank?


		@inspections = @inspections.joins(:equipment).where(equipment: {equip_type_id: params[:equip_type_id]}) unless params[:equip_type_id].blank?
		@inspections = @inspections.where("inspections.created_at > ?", params[:data1]) unless params[:data1].blank?
		@inspections = @inspections.where("inspections.created_at < ?", params[:data2]) unless params[:data2].blank?
		@inspections = @inspections.joins(:equipment).where(equipment: {building_id: params[:building_id]}) unless params[:building_id].blank?
		@inspections = @inspections.where(approved: params[:approved_id]) unless params[:approved_id].blank?
		@inspections = @inspections.where(equipment_id: params[:equipment_id]) unless params[:equipment_id].blank?
	end

  def inspection_params
    params.require(:inspection).permit(:photo_url,:user_id,:equipment_id,:description,:group_id,:approved)
  end

  def answers_params
    params.require(:inspection).permit(answers_attributes[:is_ok])
  end

end

app/helpers/inspection_helper.rb
module InspectionHelper
end

app/views/inspections/_search.html.erb
<div class="container">
  <%= form_tag(inspections_path, method: "get") do %>
  <p> Predio:
    <%= building_array = @buildings.map {|building| [building.name, building.id]}
    building_array.unshift(['',''])
    select_tag(:building_id, options_for_select(building_array)) %>

   Data da inspeção: <input type="text" name="data1" placeholder="dd/mm/aa" size="10"> a <input type="text" name="data2" placeholder="dd/mm/aa" size="10">
  </p>
  <p>

  Estagiário:
      <% user_array = @users.map {|user| [user.name, user.id]}
    user_array.unshift(['',''])%>
    <%= select_tag(:user_id, options_for_select(user_array)) %>

  Equipamento:
    <% equip_type_array = @equip_types.map {|equip_type| [equip_type.kind, equip_type.id]}
    equip_type_array.unshift(['',''])%>
    <%= select_tag(:equip_type_id, options_for_select(equip_type_array)) %>

    <%= submit_tag("Aplicar Filtros", :class => "btn default-button")%>
  </p>

    <% end %>

</div>

<!-- end -->

app/views/inspections/_search_history.html.erb
<!--form_tag welcome_index_path, :method => 'get' do -->
<div class="container">
  <%= form_tag(inspections_index_history_path, method: "get") do %>
  <p> Predio:
    <%= building_array = @buildings.map {|building| [building.name, building.id]}
    building_array.unshift(['',''])
    select_tag(:building_id, options_for_select(building_array)) %>

   Data da inspeção: <input type="text" name="data1" placeholder="dd/mm/aa" size="10"> a <input type="text" name="data2" placeholder="dd/mm/aa" size="10">
  </p>
  <p>

  Estagiário:
      <% user_array = @users.map {|user| [user.name, user.id]}
    user_array.unshift(['',''])%>
    <%= select_tag(:user_id, options_for_select(user_array)) %>

  Equipamento:
    <% equip_type_array = @equip_types.map {|equip_type| [equip_type.kind, equip_type.id]}
    equip_type_array.unshift(['',''])%>
    <%= select_tag(:equip_type_id, options_for_select(equip_type_array)) %>

    <%= submit_tag("Aplicar Filtros", :class => "btn default-button")%>
  </p>

    <% end %>

</div>

<!-- end -->

app/views/inspections/_showChecklist.erb
<% if !(@inspection.equipment.is_there)  %>
	Aviso: Equipamento Não Existe.
<% else %>

	<% if @answers.size == 0 %>
      		Nenhuma pergunta foi respondida ou está disponível para o equipamento selecionado.
    	<% end %>
    	
	<% @answers.each do |answer| %>
		
		<table class="cleartable">
        	<tr>
			<td class="td-info-x">
			<% if (answer.is_ok == 0) %>
				<span title="Sim" class="icon-ok-circle glyphicon-sim"></span>
			<% end %>
                    	<% if (answer.is_ok == 1) %>
				<span title="Não" class="icon-remove-circle glyphicon-nao"></span>
			<% end %>
                    	<% if (answer.is_ok == 2) %>
                        	<span title="Não Se Aplica" class="icon-ban-circle glyphicon-nsa"></span>
			<% end %>
            		</td>

        	    	<td width="100%" style="vertical-align:top;">
			<% if !answer.checklist_item.nil? %>
                		<strong> <%= answer.checklist_item.question %></strong>
        		<% else %>
				<strong>!!Pergunta Não Disponível!!</strong>
        		<% end %>
            		</td>
            		
		</tr>
        	<tr>	
			<td class="td-info-x">
			</td>
			<% if !answer.comment.nil? && answer.comment != "" %>
       				<td width="100%">
					Comentários: <%= answer.comment %>           		
				</td>
			<% else %>
				<td width="100%">
					Comentários: Nenhum.
				</td>
			<% end %>
		</tr>
		<% if answer.upload.size > 0 %>
		<tr>
			<td class="td-info-x">
			</td>
			<td width="100%">
				<% img_count = 0 %>

				<% if answer.upload.size > 0 %>
					<table>
	   			<% end %>

			<% answer.upload.each do |upload| %>
			<% if img_count == 0 %>
				<tr>
   			<% end %>
			<% img_count = img_count + 1 %>
		
			<td class="img-container">
				<div class="img-container">
						<a class="fancybox" rel="group-<%= answer.id%>" href="<%= upload.photo.url %>">
							<center>
								<img class="image-details borderedtable" src="<%= upload.photo.url %>" />
							</center>
						</a>
					</div>
				</td>
				<% if img_count >= 3 %>
					<% img_count = 0 %>
					</tr>
				<% end %>
				<% end %>
				<% if answer.upload.size > 0 %>
					</table>	   			
				<% end %>
			</td>
			
		</tr>
		<% end %>
		</table>
    	<% end %>
<% end %>
</table>



<% if @inspection_url != nil %>
	<hr class="hrdivider2" />

	<h3>Imagem de Referência</h3>
	<hr class="hrdivider" />

	<div class="img-container">
		<a class="fancybox" rel="master" href="<%= @inspection_url %>">
			<center>
				<img class="image-details borderedtable" src="<%= @inspection_url %>" />
			</center>
		</a>
	</div>
<% end %>

app/views/inspections/_showData.erb
<table class="table">
    <tr>
        <th>ID</th>
        <td><%= @inspection.id%></td>
    </tr>
    <tr>
        <th>Vistoria</th>
        <td><%= @inspection.group.try(:name)%></td>
    </tr>
    <tr>
        <th>Tipo do Ítem</th>
        <td><%= @inspection.equipment.equip_type.kind%></td>
    </tr>
    <tr>
        <th>Localização</th>
        <td><%= @inspection.equipment.building.name%></td>
    </tr>
    <tr>
        <th>Data da Inspeção</th>
        <td>
	<% if (@inspection.group != nil) %>
		<%= @inspection.group.vist_date %>
	<% end %>
	</td>
    </tr>
    <tr>
        <th>Inspetor</th>
        <td><%= @inspection.user.name%></td>
    </tr>
    <tr>
        <th>Descrição</th>
        <td><%= @inspection.description%></td>
    </tr>
    <tr>
        <th>Aprovado?</th>
        <td> <% if (@inspection.sent ==1)
                    %><p class="text-muted"><span class="label label-default" "text-muted">Enviado</span><% else
                if (@inspection.approved == 0)
                    %><p class="text-muted"><span class="label label-info" "text-muted">Pendente</span><% end
                if (@inspection.approved == 1)
                    %><p class="text-muted"><span class="label label-success" "text-muted">Aprovado</span><% end
                if (@inspection.approved == 2)
                    %><p class="text-muted"><span class="label label-important" "text-muted">Reprovado</span><% end
                end
                %></td>
    </tr>
</table>
<h3>Checklist - <%= @inspection.equipment.equip_type.kind%></h3>

app/views/inspections/_showInspection.erb
<style>
.img-container
{
	padding:		1px;
	width:		300px;
	height:		200px;
}

.image-details
{

	max-width:		300px;
	max-height:		200px;
}

.hrdivider
{
	border: 1px solid #000;
}

.hrdivider2
{
	border: 2px solid #000;
}

.cleartable {
	border: none;
}

.borderedtable
{
	border: 1px solid #000;
}

.td-info-x {
    width: 30px;
    height: 35px;
    display: inline-block;
    white-space: nowrap;
}


.glyphicon-sim {
    font-size: 30px;
    color: green;
}

.glyphicon-nao {
    font-size: 30px;
    color: red;
}
.glyphicon-nsa {
    font-size: 30px;
    color: blue;
}

</style>

<%= link_to "Ver Relatório Para Impressão", report_path(t: 1, id: @inspection.id), target: "_blank" %>
<br/> 
<%= render :partial => 'inspections/showData' %>

<hr class="hrdivider2" />

<%= render :partial => 'inspections/showReference' %>

<%= render :partial => 'inspections/showChecklist' %>

<hr class="hrdivider2" />

<div class="container">
  <table>
    <tr>
      <% if (@inspection.approved == 0) then %>
      <% if (current_user.kind == "admin") %>
      <td>
        <%= link_to 'Aprovar', "javascript:void(0)",  method: :validate,  :onclick => "approve();", class: "btn btn-success"%>
      </td>
      <td>
        <%= link_to 'Reprovar', "javascript:void(0)",  method: :disapprove,  :onclick => "repprove();", class: "btn btn-danger" %>
      </td>
      <!--% else %>
        Apenas Adminstradores podem aprovar ou reprovar inspeções!-->
      <% end %>
      <% end %>

    </tr>
  </table>
</div>

<script type="text/javascript">
	function approve() {
		if (confirm('Certeza que deseja aprovar a inspeção?')) {
			//approve with ajax
			$.ajax({
				type: "GET",
				url: "validate",
				data: {id:<%=@inspection.id%>}
				}
			).done(function() {
  				window.location.reload(true);
			}
			);
			
		}
	}
	
	function repprove() {
		if (confirm('Certeza que deseja reprovar a inspeção?')) {
			//repprove with ajax
			$.ajax({
				type: "GET",
				url: "disapprove",
				data: {id:<%=@inspection.id%>}
				}
			).done(function() {
  				window.location.reload(true);
			}
			);
		}
	}

//make the img fix
//$('img').error(function(){
//       	$(this).hide();
//});

//$( document ).ready(function() {
//	if ( $.browser.msie && $.browser.version < 9 ) {
//		$('img').each(function(){
//     			$(this).attr('src', $(this).attr('src'));
//		});
//	}	
//});
</script>

app/views/inspections/disapprove.html.erb
<h1>Inspection#disapprove</h1>
<p>Find me in app/views/inspection/disapprove.html.erb</p>

app/views/inspections/edit.html.erb
<style>
.img-container{
    padding:        1px;
    max-width:      250px;
    max-height:     150px;
}
</style>

<script language="javascript">
  var needToConfirm = true;
  window.onbeforeunload = confirmExit;
  function confirmExit()
  {
    if (needToConfirm) {
    	return "Você deseja mesmo sair desta página?";
    }
  }
  function submitConfirm()
  {
  	needToConfirm = false; 
  	save = confirm('Deseja Salvar?');
  	if (!save) needToConfirm = true;
  	return save;
  }
</script>

<h1>Checklist</h1>
<hr>

<%= form_for @inspection, :html => {:multipart => :true } do |f| %>

<%= f.label :group_id, "Grupo Da Inspeção"%>
<%= f.collection_select :group_id, Group.all.order(:name), :id, :name %>
<% prev_id = nil%>
<% quests = @questions %>
<% num_quest = 1 %>
<% total_quest = @questions.size %>
<hr>
Perguntas  
<% @questions.each do |id, question, q| %>
	<a href="javascript:void(0);" onclick="$('.quest_hide').hide(); $('#checklist_item_<%= id%>').show();"><%= num_quest %></a>
	<% num_quest = num_quest + 1 %>
<% end %>
<hr>
<% num_quest = 1 %>
<% @questions.each do |id, question, q| %>
  	<div class="quest_hide" id="checklist_item_<%= id%>" style="display:none;">
  		Pergunta <%= num_quest %>/<%= total_quest%>
  		<% num_quest = num_quest + 1 %>
  		<% question_id = id %>
  		<%= label_tag question, question %>  
  		<%= select('answers', id, @answertypes, :selected => @answer_data.where(checklist_item_id: id).first.try(:is_ok)) %>
	
	  <%= label_tag "foto" ,"Escolha uma ou mais fotos para esta pergunta" %>
	  <%= file_field :photos, id, :multiple => true %>

	  <%= label_tag "foto_r", "Fotos Atuais"%>
	  <% answer_first = @answer_data.where(checklist_item_id: question_id).first %>
  
	  <% uploads = Upload.where(answer_id: answer_first.try(:id)) %>
	  <% if uploads.size < 1 %>
		Nenhuma foto foi carregada para esta pergunta.
	  <% else %>
	    Foram/Foi carregada(s) <%= uploads.size %> foto(s) para esta pergunta.
	  <% end %>
	  <% for i in 0..(uploads.size-1) %>
		<% up_id = uploads[i].id %>
		<% up_url = uploads[i].photo.url %>
	        <% table_id = "table_" + up_id.to_s %>
		<table id='<%= table_id %>'>
		<tr>
			<td>
				<div>
					<a class="fancybox" rel="group-<%= id%>" href="<%= up_url %>">
						<img class="img-container borderedtable" src="<%= up_url %>" />
					</a>		
				</div>
			</td>
			<td>
				<a href='javascript:void(0);' onclick='remove_upload_ajax(<%= up_id %>);'>Remover</a>
			</td>
		</tr>
		</table>
  	<% end %>
  
  	<%= label_tag "comment", "Comentário" %>
  	<%= text_area_tag "comment_" + id.to_s, @answer_data.where(checklist_item_id: id).first.try(:comment) %>

	</div> <!--//Checklist item end -->

<% end %>
<br/>
<%= f.submit "Salvar", :class => "btn default-button", :onclick => "return submitConfirm();"%>

<% end %>

<script type="text/javascript">
function remove_upload_ajax(idupload)
{
	//question
	var ask = confirm("Você deseja remover esta imagem?");
	if (!ask) return;

	//ajax
	$.ajax({
        url: '<%= inspections_removephoto_path %>',
        data: { idphoto: idupload} ,
        success: function (response) {
            $a = $("#table_" + idupload);
			$a.remove();
			alert( "Remoção Bem Sucedida!" );
        },
        error: function () {
            alert( "Erro na Remoção da Imagem!" );
        }
    });

	//tablehide

}
</script>

app/views/inspections/index.html.erb
<div id="search_block" class="search" style="display: none;">
  <%= render :partial => 'search' %>
</div>



<i><%= link_to "[Criar Nova Inspeção]", new_inspection_path %></i>
<i><a href="javascript:void(0);" onclick="$('#tab_list').toggle(); $('#tab_hidden').toggle();">[Alternar Visão]<a/></i>
<i><%= link_to "[Filtros]", "javascript:void(0);", onclick: "$('#search_block').toggle();", style: "float:right;"%></i>
<div id="tab_list" style="display:none;">
<table class="table table-striped table-hover">
    <tr>
        <!--th></th-->
        <th>Vistoria</th>
        <th>Equipamento</th>
        <th>Localização</th>
        <th>Data da Inspeção</th>
        <th>Inspetor</th>
        <th>Aprovado</th>
        <th></th>
        <th></th>
    </tr>
    <% @inspections.each do |insp| %>
        <tr>
            <!--td>
               <%= insp.id %>
            </td-->
            <td>
               <%= insp.group.try(:name) %>
            </td>
            <td>
                <%= insp.equipment.name %> (<%= insp.equipment.equip_type.kind %>)
            </td>
            <td>
               <%= insp.equipment.building.name %>
            </td>
            <td>
               <% if (insp.group != nil) %>
	       	<%= insp.group.vist_date %>
	       <% else %>
		Sem Data Definida
	       <% end %>
            </td>
            <td>
                <%= insp.user.name %>
            </td>
            <td>
                <% if (insp.sent == 1)
                    %><p class="text-muted">Enviado</p><% else
                if (insp.approved == 0)
                    %><p class="text-muted">Pendente</p><% end
                if (insp.approved == 1)
                    %><p class="text-muted">Aprovado</p><% end
                if (insp.approved == 2)
                    %><p class="text-muted">Reprovado</p><% end
                end
                %>
            </td>
            <td>
                    <%= link_to "Visualizar", insp  %>

            </td>
            <td>
                <% if (insp.equipment.is_there)  %>
                    <%= link_to "Checklist", edit_inspection_path(:id => insp.id) %>
                <% end %>
            </td>
        </tr>
    <% end -%>
</table>
</div>
<div id="tab_hidden">
	<% @buildings.each do |loc| %>
		<a onclick="$('#bld_<%=loc.id%>').toggle();"><i class="icon-chevron-right"></i><%= loc.name%></a>
		<% vistorias = Group.where(building_id: loc.id).order("name")%>
		(<%= vistorias.size%> vistoria(s))<br/>
		<div id="bld_<%=loc.id%>" style="display:none;">
		<% vistorias.each do |vis| %>
			<div style="padding-left: 15px;" id="vist_<%=vis.id%>"><a onclick="$('#vis_<%=vis.id%>').toggle();"><i class="icon-chevron-right"></i><%= vis.name%></a>
			<% inspections = Inspection.joins(:equipment).where(approved: 0).where(group_id: vis.id).order("equipment.name")%>
			- <%=vis.vist_date %> (<%= inspections.size%> inspeção(ões))</div>
			<div id="vis_<%=vis.id%>" style="display:none;">
			<% inspections.each do |insp| %>
				<div style="padding-left: 35px;" id="insp_<%=insp.id%>"><i class="icon-file"></i><%= insp.equipment.equip_type.kind %> - <%= insp.equipment.name %> (<%= insp.description%>). Por <%= insp.user.name%>. 
				<%= link_to "[Visualizar]", insp  %> 
				<% if (insp.equipment.is_there)  %>
                    <%= link_to "[Editar Checklist]", edit_inspection_path(:id => insp.id) %>
                <% end %>
                </div>
			<% end %>
			</div>
		<% end %>
		</div>
	<% end %>
	<br/>
</div>

app/views/inspections/index_history.html.erb
<div id="search_block" class="search" style="display: none;">
  <%= render :partial => 'search_history' %>
</div>

<i><%= link_to "[Criar Nova Inspeção]", new_inspection_path %></i>
<i><%= link_to "[Filtros]", "javascript:void(0);", onclick: "$('#search_block').toggle();", style: "float:right;"%></i>

<table class="table table-striped table-hover">
    <tr>
        <th></th>
        <th>Equipamento</th>
        <th>Localização</th>
        <th>Data da Inspeção</th>
        <th>Inspetor</th>
        <th>Aprovado</th>
        <th></th>
    </tr>
    <% @inspections.each do |insp| %>
        <tr>
            <td>
               <%= insp.id %>
            </td>
            <td>
                <%= insp.equipment.equip_type.kind %>
            </td>
            <td>
               <%= insp.equipment.building.name %>
            </td>
            <td>
               <% if (insp.group != nil) %> 
	       	<%= insp.group.vist_date %> 
	       <% else %>
		Sem Data Definida
	       <% end %>
            </td>
            <td>
                <%= insp.user.name %>
            </td>
            <td>
                <% 
                if (insp.sent == 1)
                    %><p class="text-muted">Enviado</p><% else
                if (insp.approved == 0)
                    %><p class="text-muted">Pendente</p><% end
                if (insp.approved == 1)
                    %><p class="text-muted">Aprovado</p><% end
                if (insp.approved == 2)
                    %><p class="text-muted">Reprovado</p><% end
                end
                %>
            </td>
            <td>
                    <%= link_to "Visualizar", insp  %>

            </td>
        </tr>
    <% end -%>
</table>

app/views/inspections/show.html.erb
<style>
.imgi-container{
    padding:        1px;
    width:      650px;
    height:     550px;
}

.imagi-details{
    max-width:      650px;
    max-height:     550px;
}
</style>

</br>
<h3>Visualização de Inspeção</h3>

<%= render :partial => 'showInspection' %>

<%= link_to "Nova Inspeção", new_inspection_path %>

app/views/inspections/validate.html.erb
<h1>Inspection#validate</h1>
<p>Find me in app/views/inspection/validate.html.erb</p>